### ISSUE TITLE
error

### ISSUE THREAD

**Issue by George874248** [rikkimongoose/JSonCmp#1]
JSonCmp({}, {a:"ASDASD" , B: "SSSSS"}) return true;
JSonCmp({a:"ASDASD" , B: "SSSSS"}, {}) return false;

you can do in you code 
current code: return doComparation(src1, src2, options);
new code: 
var flag = return doComparation(src1, src2, options);
if(flag == true) return doComparation(src2, src1, options);

it's not optimised but it works.

**Comment by rikkimongoose** [comment]
Thank you! I've included your fix to new release.

It's surprising for me that someone else uses this script too.
